language: python

python:
  - "3.8"

# command to install dependencies

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest